import { useEffect, useMemo, useState } from 'react';
import { Link } from 'wouter';
import { ArrowLeft, Castle, ChevronRight, Coins, Flag, RefreshCw, Shield, Swords, Trophy, Users } from 'lucide-react';
import { useGetClashDashboard } from '@workspace/api-client-react';
import { AppSidebar } from '@/components/app-sidebar';
import { ClashIQInlineBanner } from '@/components/clashiq-inline-banner';

type D=Record<string, any>;
const obj=(v:any):D=>v&&typeof v==='object'?v:{};
const arr=(v:any):D[]=>Array.isArray(v)?v.map(obj):[];
const n=(v:any)=>typeof v==='number'?v:0;
const s=(v:any,f='—')=>typeof v==='string'?v:f;
const fmt=(v:any)=>{const d=new Date(s(v,''));return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('en-US',{day:'numeric',month:'short',year:'numeric'}).format(d)};
const compact=(v:number)=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(v);

export default function CapitalRaidsPage(){
 const {data,isLoading,isError,refetch}=useGetClashDashboard(); const [selected,setSelected]=useState(0);
 const d=data as any; const clan=obj(d?.clan); const seasons=useMemo(()=>arr(d?.capitalRaidSeasons),[d?.capitalRaidSeasons]); const season=seasons[selected]??seasons[0]??{};
 const members=arr(season.members).sort((a,b)=>n(b.capitalResourcesLooted)-n(a.capitalResourcesLooted));
 if(isLoading)return <div className="grid min-h-[100dvh] place-items-center bg-background"><b>Loading Capital Raids…</b></div>;
 if(isError)return <div className="grid min-h-[100dvh] place-items-center bg-background p-6"><section className="rounded-3xl border border-card-border bg-card p-8 text-center"><h1 className="font-display text-2xl font-bold">Could not load Capital Raids</h1><button onClick={()=>void refetch()} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-primary-foreground"><RefreshCw className="size-4"/>Try again</button></section></div>;
 return <div className="flex min-h-[100dvh] bg-[#07090d] text-white"><AppSidebar clanName={s(clan.name,'Mecka Clash')} clanTag={s(d.clanTag,'#2Q0Q82C9R')} />
 <main className="min-w-0 flex-1 !ml-0 !pl-0" style={{ width: "calc(100% - 260px)", maxWidth: "calc(100% - 260px)" }}>
 <ClashIQInlineBanner />
<header className="border-b border-border/80 bg-background/80 px-5 py-4 backdrop-blur-md"><div className="mx-auto flex max-w-[1200px] items-center justify-between"><div><Link href="/" className="inline-flex items-center gap-2 text-xs font-bold text-primary"><ArrowLeft className="size-4"/>Overview</Link><h1 className="mt-2 font-display text-2xl font-bold tracking-[-.05em]">Capital Raids</h1></div><button onClick={()=>void refetch()} className="grid size-9 place-items-center rounded-xl border border-border bg-card"><RefreshCw className="size-4"/></button></div></header>
 <div className="mx-auto max-w-[1200px] space-y-5 px-5 py-6 md:px-8 md:py-8"><section className="rounded-3xl bg-sidebar p-6 text-sidebar-foreground shadow-xl md:p-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-sidebar-accent">Mecka Clash / Capital</p><h2 className="mt-2 font-display text-3xl font-bold">Capital Raids</h2><p className="mt-2 text-sm text-sidebar-foreground/60">History of raid seasons, loot and participation.</p></div><div className="grid grid-cols-2 gap-4"><div><p className="text-[10px] uppercase tracking-[.14em] text-sidebar-foreground/45">Capital points</p><p className="mt-1 font-data text-2xl font-bold">{compact(n(clan.clanCapitalPoints))}</p></div><div><p className="text-[10px] uppercase tracking-[.14em] text-sidebar-foreground/45">League</p><p className="mt-1 font-bold">{s(clan.capitalLeague,'—')}</p></div></div></div></section>
 {seasons.length===0?<section className="rounded-2xl border border-card-border bg-card p-8 text-center"><Castle className="mx-auto size-8 text-muted-foreground"/><h2 className="mt-4 font-bold">No Capital Raid data yet</h2><p className="mt-2 text-sm text-muted-foreground">When the Clash API returns a raid season, it will appear here automatically.</p></section>:<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-card-border bg-card p-4"><Coins className="size-4 text-[#9c6e00]"/><p className="mt-3 text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">Raid loot</p><p className="mt-1 font-data text-2xl font-bold">{compact(n(season.capitalTotalLoot))}</p></div><div className="rounded-2xl border border-card-border bg-card p-4"><Swords className="size-4 text-primary"/><p className="mt-3 text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">Raids</p><p className="mt-1 font-data text-2xl font-bold">{n(season.raidsCompleted)}</p></div><div className="rounded-2xl border border-card-border bg-card p-4"><Users className="size-4 text-primary"/><p className="mt-3 text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">Members</p><p className="mt-1 font-data text-2xl font-bold">{members.length}</p></div><div className="rounded-2xl border border-card-border bg-card p-4"><Trophy className="size-4 text-[#9c6e00]"/><p className="mt-3 text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">Raid rewards</p><p className="mt-1 font-data text-2xl font-bold">{n(season.offensiveReward)+n(season.defensiveReward)}</p><p className="mt-1 text-[10px] text-muted-foreground">Offense + defense</p></div></section>
 <section className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><article className="rounded-2xl border border-card-border bg-card p-5 shadow-sm"><h2 className="font-bold">Raid seasons</h2><div className="mt-4 space-y-2">{seasons.map((x,i)=><button key={i} onClick={()=>setSelected(i)} className={`w-full rounded-xl p-3 text-left ${i===selected?'bg-primary text-primary-foreground':'bg-secondary/50'}`}><div className="flex items-center justify-between"><span className="text-xs font-bold">{fmt(x.startTime)} – {fmt(x.endTime)}</span><ChevronRight className="size-4"/></div><p className={`mt-1 text-[10px] ${i===selected?'opacity-80':'text-muted-foreground'}`}>{s(x.state,'completed')} · {compact(n(x.capitalTotalLoot))} loot</p></button>)}</div></article><article className="rounded-2xl border border-card-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold">Participants</h2><span className="text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">Loot</span></div>{members.length?<div className="mt-4 divide-y divide-border/60">{members.map((m,i)=><div key={i} className="flex items-center gap-3 py-3"><div className="grid size-9 place-items-center rounded-xl bg-secondary font-bold text-xs">{String(m.name??'?').slice(0,2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{s(m.name)}</p><p className="text-[10px] text-muted-foreground">{s(m.tag)} · {n(m.attacks)}/{n(m.attackLimit) + n(m.bonusAttackLimit)} attacks</p></div><div className="text-right"><p className="font-data text-sm font-bold">{compact(n(m.capitalResourcesLooted))}</p><p className="text-[10px] text-muted-foreground">loot</p></div></div>)}</div>:<p className="mt-4 text-sm text-muted-foreground">No member details are available for this season.</p>}</article></section></>}
 </div></main></div>;
}
